# Generated by Django 2.1.5 on 2019-02-23 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('coleccion', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('paginas', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('anio', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salidapor', models.CharField(choices=[('1', 'Venta'), ('2', 'Distribución'), ('3', 'Donación')], max_length=1)),
                ('entrada', models.BooleanField(default=False)),
                ('entradapor', models.CharField(choices=[('1', 'Impresión'), ('2', 'Distribución')], max_length=1)),
                ('cantidad', models.PositiveIntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Libro')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Libro')),
                ('puntodeventa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PuntoDeVenta')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='puntodeventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PuntoDeVenta'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('libro', 'puntodeventa')},
        ),
    ]
