# Generated by Django 2.2.5 on 2019-11-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='puntodeventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PuntoDeVenta', verbose_name='Punto de venta'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='puntodeventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.PuntoDeVenta', verbose_name='Punto de venta'),
        ),
    ]
