# Generated by Django 2.1.5 on 2019-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20190223_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='entrada',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='entradapor',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='salidapor',
        ),
        migrations.AddField(
            model_name='orden',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orden',
            name='tipodeorden',
            field=models.CharField(choices=[('1', 'Salida - Venta'), ('2', 'Salida - Distribución'), ('3', 'Salida - Donación'), ('4', 'Entrada - Impresión'), ('5', 'Entrada - Distribución')], default='1', max_length=1),
        ),
    ]
