# Generated by Django 2.2.5 on 2020-02-12 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20191120_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='libro',
        ),
        migrations.AlterField(
            model_name='orden',
            name='puntodeventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.PuntoDeVenta', verbose_name='Punto de venta'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='puntodeventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.PuntoDeVenta', verbose_name='Punto de venta'),
        ),
        migrations.CreateModel(
            name='RenglonOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Orden')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Libro')),
            ],
        ),
    ]
