# Generated by Django 2.2.5 on 2020-02-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200212_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renglonorden',
            old_name='cabecera',
            new_name='orden',
        ),
    ]
