# Generated by Django 2.1.5 on 2019-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_orden_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
