# Generated by Django 2.2.5 on 2020-02-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20200212_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renglonorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Orden'),
        ),
    ]
