# Generated by Django 2.1.5 on 2019-02-23 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20190223_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='fecha',
            new_name='fechaorden',
        ),
    ]
