# Generated by Django 2.1.5 on 2019-03-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_orden_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='user',
        ),
    ]
