# Generated by Django 2.1.5 on 2019-03-09 16:25

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_orden_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenClasificada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='orden',
            name='tipodeorden',
        ),
        migrations.AddField(
            model_name='ordenclasificada',
            name='tipoorden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.TipoOrden'),
        ),
        migrations.AddField(
            model_name='orden',
            name='ordeningresada',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tipoorden', chained_model_field='tipoorden', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.OrdenClasificada'),
        ),
    ]
