# Generated by Django 2.1.5 on 2019-03-09 21:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_auto_20190309_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ordenclasificada',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='tipoorden', chained_model_field='tipoorden', on_delete=django.db.models.deletion.CASCADE, to='inventario.OrdenClasificada'),
        ),
    ]
