# Generated by Django 2.1.5 on 2019-03-09 21:33

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20190309_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ordenclasificada',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='tipoorden', chained_model_field='tipoorden', horizontal=True, to='inventario.OrdenClasificada', verbose_name='ordenclasificada'),
        ),
    ]
