# Generated by Django 2.1.5 on 2019-03-09 22:02

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20190309_2133'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='orden',
            name='tipoorden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.TipoOrden'),
        ),
        migrations.AddField(
            model_name='orden',
            name='ordenclasificada',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='tipoorden', chained_model_field='tipoorden', default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.OrdenClasificada'),
        ),
        
    ]
