# Generated by Django 2.1.5 on 2019-03-09 22:15

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_auto_20190309_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ordenclasificada',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='tipoorden', chained_model_field='tipoorden', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.OrdenClasificada'),
        ),
    ]
