# Generated by Django 2.1.5 on 2019-03-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_auto_20190310_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='coleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Coleccion'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Libro'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='puntodeventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.PuntoDeVenta'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.Libro'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='puntodeventa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.PuntoDeVenta'),
        ),
    ]
